version: '3'
services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:443"
    ports:
      - "80:5000"
      - "443:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  web:
    build:
      context: ./  # Path to the directory containing your Dockerfile and application code
      dockerfile: Dockerfile  # Name of your Dockerfile (if not named Dockerfile)
    container_name: my-app
    ports:
      - "5000:5000"
    environment:
      - SPOTIPY_CLIENT_ID=10b91af54fbd480a814673587a528998
      - SPOTIPY_CLIENT_SECRET=3d1fc19679ac4cfc8e32b54df95dc7ff
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reddit_comment_api.rule=Host(`songlinkgenerator.adadkins.com`)"
      - "traefik.http.routers.reddit_comment_api.entrypoints=web"